resolver: nightly-2016-05-13
packages:
- '.'
- example/
- location:
    git: https://github.com/GetShopTV/swagger2.git
    commit: 863b414893da1db41da6a6e22dc4933684e29da9
  extra-dep: true
extra-deps:
- aeson-0.11.2.0
- doctest-0.11.0
- servant-0.5
- servant-server-0.5
- servant-swagger-1.0.3
- swagger2-2.0.1
flags: {}
